services:
    backend:
        build: ./backend
        container_name: backend
        restart: always
        ports:
            - "3000:3000"
        env_file:
            - ./backend/.env

    frontend:
        build: ./frontend
        container_name: frontend
        restart: always
        ports:
            - "3001:80"
        depends_on:
            - backend
