export const BadResponseCode = {
    INVALID_TOKEN: "INVALID_TOKEN",
    MISSING_TOKEN: "MISSING_TOKEN",
    EXPIRED_TOKEN: "EXPIRED_TOKEN",
    INACTIVE_TOKEN: "INACTIVE_TOKEN",
    INSUFFICIENT_RIGHTS: "INSUFFICIENT_RIGHTS",
    OBJECT_NOT_FOUND: "OBJECT_NOT_FOUND",
    MISSING_REQUEST_DATA: "MISSING_REQUEST_DATA",
    INVALID_API_KEY: "INVALID_API_KEY",
    DATABASE_CONFLICT: "DATABASE_CONFLICT",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
} as const;

export type BadResponseCode = (typeof BadResponseCode)[keyof typeof BadResponseCode];
